import type { TypeId } from "./content";
import type { Lang } from "./i18n";

export const CHALLENGE_TEXT = {
  ja: {
    navTitle: "精密チャレンジ",
    introTitle: "精密チャレンジ",
    introLead: "本診断は「自分ではどう感じるか」を聞くものでした。ここでは、頭の中の処理を実際に測ります。結果は本診断と並べて表示されます。",
    introSteps: ["図形回転：2つの立体が同じ形か、鏡に映した形かを判断（8問）", "見た目の記憶：絵を6秒見て、何がどこにあったかを答える（6問）", "イメージの鮮明さ：頭の中に浮かぶ映像や音の鮮やかさを答える（6問）"],
    introTime: "所要時間 約3分・音は使いません",
    introNeedResult: "先に本診断を受けると、結果と並べて比べられます。",
    start: "はじめる",
    takeMain: "本診断を受ける",
    rotTitle: "図形回転",
    rotHelp: "右の立体は、左の立体を回したものですか？それとも鏡に映した形ですか？",
    rotSame: "同じ形",
    rotMirror: "鏡に映した形",
    memTitle: "見た目の記憶",
    memStudy: "6秒間、よく見て覚えてください",
    memWhatAt: "印の位置にあったのは？",
    memWhereIs: "これはどこにあった？",
    vivTitle: "イメージの鮮明さ",
    vivHelp: "目を閉じて思い浮かべ、どのくらい鮮明かを選んでください。",
    vivScale: ["まったく浮かばない", "ぼんやり", "まあまあ", "はっきり", "実物と同じくらい鮮明"],
    finishing: "結果をまとめています…",
    resultTitle: "精密チャレンジの結果",
    resultNote: "実測は「目安」です。母集団の基準値ではなく、偶然の正答率を差し引いて0〜100にしています。",
    rotLabel: "図形回転（3Dの実測）",
    memLabel: "見た目の記憶（カメラの実測）",
    vivLabel: "イメージの鮮明さ",
    selfLabel: "自覚",
    measuredLabel: "実測",
    correctOf: "%s問正解",
    avgTime: "平均 %s秒",
    gapHigher: "自覚より実測の方が高めです。「%s」の処理を、思っている以上に使える可能性があります。",
    gapLower: "自覚の方が実測より高めです。「%s」の処理を好んで使っている一方、精度より慣れや好みで選んでいるのかもしれません。",
    gapMatch: "自覚と実測がおおむね一致しています。",
    weakVisual: "視覚的なイメージがほとんど浮かばないと答えています。頭の中で映像を思い浮かべにくい人（アファンタジア）は珍しくなく、言葉や音、知識の構造で考えるのが得意なことも多いです。",
    weakAuditory: "頭の中で音や声がほとんど再生されないと答えています。音のイメージを持ちにくい人も一定数いて、その分ほかの処理で補っていることが多いです。",
    ctaTitle: "精密チャレンジで実測する",
    ctaDesc: "図形回転・見た目の記憶・イメージの鮮明さを約3分で測り、自覚とのずれを見られます。",
    ctaBtn: "チャレンジする",
    retry: "もう一度チャレンジ",
  },
  en: {
    navTitle: "Deep Challenge",
    introTitle: "Deep Challenge",
    introLead: "The main assessment asked how things feel to you. Here we measure how your mind actually processes information, and show it next to your main result.",
    introSteps: ["Mental rotation: decide whether two 3D shapes are the same or mirror images (8 trials)", "Visual memory: look at a picture for 6 seconds, then recall what was where (6 questions)", "Imagery vividness: rate how vivid your mental images and sounds are (6 questions)"],
    introTime: "About 3 minutes · No sound needed",
    introNeedResult: "Take the main assessment first to compare the two side by side.",
    start: "Start",
    takeMain: "Take the main assessment",
    rotTitle: "Mental rotation",
    rotHelp: "Is the right shape a rotated version of the left one, or its mirror image?",
    rotSame: "Same shape",
    rotMirror: "Mirror image",
    memTitle: "Visual memory",
    memStudy: "Study this for 6 seconds",
    memWhatAt: "What was in the marked spot?",
    memWhereIs: "Where was this?",
    vivTitle: "Imagery vividness",
    vivHelp: "Close your eyes, imagine it, and choose how vivid it is.",
    vivScale: ["Nothing at all", "Faint", "Moderate", "Clear", "As vivid as real"],
    finishing: "Putting your results together…",
    resultTitle: "Deep Challenge results",
    resultNote: "Measured scores are rough guides, not population norms. Chance-level guessing is subtracted and scaled to 0–100.",
    rotLabel: "Mental rotation (3D, measured)",
    memLabel: "Visual memory (Camera, measured)",
    vivLabel: "Imagery vividness",
    selfLabel: "Self-report",
    measuredLabel: "Measured",
    correctOf: "%s correct",
    avgTime: "avg %ss",
    gapHigher: "Your measured score is higher than your self-report. You may be able to use \"%s\" processing more than you think.",
    gapLower: "Your self-report is higher than your measured score. You may prefer \"%s\" processing out of habit or liking rather than precision.",
    gapMatch: "Your self-report and measured score roughly match.",
    weakVisual: "You reported almost no visual imagery. Many people can't picture images in their mind (aphantasia), and they often think well in words, sounds, or structured knowledge.",
    weakAuditory: "You reported that sounds and voices barely play in your head. Some people have little auditory imagery and rely more on other kinds of processing.",
    ctaTitle: "Measure it with the Deep Challenge",
    ctaDesc: "In about 3 minutes, measure mental rotation, visual memory, and imagery vividness, and see how they compare with your self-report.",
    ctaBtn: "Take the challenge",
    retry: "Try the challenge again",
  },
} as const satisfies Record<Lang, Record<string, string | readonly string[]>>;

export const VIVIDNESS_PROMPTS: Record<TypeId, Record<Lang, string>> = {
  camera: { ja: "よく知っている人の顔を思い浮かべてください。目元や髪型などの細部は、どのくらいはっきり見えますか？", en: "Picture the face of someone you know well. How clearly can you see details like their eyes or hairstyle?" },
  "3d": { ja: "自宅の玄関から台所まで歩くところを想像してください。曲がる向きや距離感まで、どのくらいはっきりたどれますか？", en: "Imagine walking from your front door to your kitchen. How clearly can you follow the turns and distances?" },
  fantasy: { ja: "「夕暮れの海辺を、白い犬が駆けていく」。この文から、場面がどのくらい鮮明に浮かびますか？", en: "\"A white dog runs along the beach at sunset.\" How vividly does the scene appear from this sentence?" },
  dictionary: { ja: "「旅行の持ち物」を考えてください。必要なものが、分類されたリストのような言葉として、どのくらいはっきり並びますか？", en: "Think of \"things to pack for a trip.\" How clearly do the items line up as words, like a categorized list?" },
  radio: { ja: "知っている人の声で「おはよう」と言われるのを想像してください。その声は、どのくらいはっきり聞こえますか？", en: "Imagine someone you know saying \"good morning.\" How clearly can you hear their voice?" },
  sound: { ja: "よく知っている曲のサビを、頭の中で再生してください。メロディや音色は、どのくらいはっきり聞こえますか？", en: "Play the chorus of a familiar song in your head. How clearly can you hear the melody and sound?" },
};
